MarCom/MarCom.Presentation/Controllers/MenuAccessController.cs
using MarCom.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarCom.Presentation.Controllers
{
    public class MenuAccessController : Controller
    {
        // GET: MenuAccess
        public ActionResult Index()
        {
            return View();
        }

        //GET: List
        public ActionResult List()
        {
            return PartialView("_List", MenuAccessRepo.Get());
        }
    }
}

MarCom/MarCom.Presentation/Views/MenuAccess/Index.cshtml
@model MarCom.ViewModel.EmployeeViewModel

@{
    ViewBag.Title = "Menu Access";
}

@Styles.Render("~/ AdminLTE / plugins / datatables / css")
<div class="panel panel-danger">
    <div class="panel-heading">
        <div class="row">
            <div class="col-offset-11">
                <h3>List Menu Access</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-offset-11">
                <button type="button" id="btn-new" class="btn btn-primary btn-sm">Add</button>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <input type="text" class="form-control" placeholder="Select Role Code" />
                </div>
                <div class="col-xs-3">
                    <input type="text" class="form-control" placeholder="Select Role Name" />
                </div>
                <div class="col-xs-2">
                    <input type="text" class="form-control" placeholder="Created" />
                </div>
                <div class="col-xs-2">
                    <input type="text" class="form-control" placeholder="Created By" />
                </div>
                <div class="col-lg-offset-11">
                    <button type="button" id="btn-new" class="btn btn-warning btn-sm">Search</button>
                </div>

            </div>
            <div class="col-lg-12" id="table-list">
                <h3>Loading...</h3>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    @Scripts.Render("~/AdminLTE/plugins/datatables/js")
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });

        $("#btn-new").click(function () {
            $(".modal-title").html("Add Employee");
            $.ajax({
                url: '@Url.Action("Create","MenuAccess")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        });

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "MenuAccess")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                },
                error: function (err) {
                    $("#table-list").tml(err);
                }
            });
        }
    </script>
}

MarCom/MarCom.Presentation/Views/MenuAccess/_List.cshtml
@model IEnumerable<MarCom.ViewModel.MenuAccessViewModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.M_Role_Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Create_Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Create_By)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.M_Role_Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Create_Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Create_By)
        </td>
        <td>
            <div class="btn-group-sm">
                <button type="button" class="btn btn-warning btn-primary" data-id="@item.Id" title="View">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
                <button type="button" class="btn btn-warning btn-edit" data-id="@item.Id" title="Edit">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                </button>
                <button type="button" class="btn btn-danger btn-delete" data-id="@item.Id" title="Delete">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </button>
            </div>
        </td>
    </tr>
}

</table>

<script type="text/javascript">
    $(".table").DataTable();
    $(".btn-edit").click(function () {
        $(".modal-title").html("Update Menu Access");
        $.ajax({
            url: '@Url.Action("Edit", "MenuAccess")',
            type: 'get',
            data: { id: $(this).attr('data-id') },
            success: function (result) {
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }

        });
    });

</script>

<script type="text/javascript">
    $(".btn-delete").click(function () {
        $(".modal-title").html("Delete Data");
        $.ajax({
            url: '@Url.Action("Delete", "MenuAccess")',
            type: 'get',
            data: { id: $(this).attr('data-id') },
            success: function (result) {
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }

        });
    });
</script>